[package]
name = "optionSimProj"
version = "0.1.0"
edition = "2021"

[dependencies]
libm = "0.2.11"

rand = "0.8"
rand_distr = "0.4"

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

gnuplot = "0.0.44"
